/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Medico;


import Modelo.CasosCovid;
import Modelo.Empleado;
import Modelo.Vacunas;
import Modelo.VacunasAplicadas;
import Vista.JframeSalario;
import java.util.ArrayList;

/**
 *
 * @author Mateo Leon
 */
public class JframeMedico extends javax.swing.JFrame {
    ArrayList<Vacunas> vacunas = new ArrayList();
    ArrayList<CasosCovid> casoscovid = new ArrayList();
    ArrayList<VacunasAplicadas> vacunasAplicadas = new ArrayList();
    
   
    
    Empleado auxEmpleado;
    /**
     * Creates new form panelAdmin
     * @param empleado
     */
    public JframeMedico(Empleado empleado) {
        initComponents();
        this.auxEmpleado = empleado;
        
         casoscovid.add(new CasosCovid(101010,"Juan","Guerra","5/10/2020"));
         casoscovid.add(new CasosCovid(123546,"Gabriela","Delgado","5/12/2020"));
         casoscovid.add(new CasosCovid(789146,"Juan","Gomez","5/6/2020"));
         casoscovid.add(new CasosCovid(188973,"Juan","","5/8/2020"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVacunas = new javax.swing.JButton();
        btnContagios = new javax.swing.JButton();
        btnAplicadas = new javax.swing.JButton();
        btnSalario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 550));

        jPanel2.setBackground(new java.awt.Color(186, 200, 211));
        jPanel2.setForeground(new java.awt.Color(0, 80, 239));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manejo COVID");

        jLabel2.setText("Panel Medico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6))
        );

        btnVacunas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVacunas.setText("Vacunas Ingresadas");
        btnVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunasActionPerformed(evt);
            }
        });

        btnContagios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnContagios.setText("Personas en cuidados intensivos");
        btnContagios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContagiosActionPerformed(evt);
            }
        });

        btnAplicadas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAplicadas.setText("Vacunas aplicadas");
        btnAplicadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicadasActionPerformed(evt);
            }
        });

        btnSalario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalario.setText("Salario");
        btnSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVacunas)
                    .addComponent(btnAplicadas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContagios)
                    .addComponent(btnSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVacunas)
                    .addComponent(btnContagios))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicadas)
                    .addComponent(btnSalario))
                .addGap(0, 253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunasActionPerformed
        JframeVacunas menuPrincipal = new JframeVacunas(this.vacunas);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVacunasActionPerformed

    private void btnSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalarioActionPerformed
        JframeSalario menuPrincipal = new JframeSalario(this.auxEmpleado);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnSalarioActionPerformed

    private void btnContagiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContagiosActionPerformed
        JframeContagios menuPrincipal = new JframeContagios(this.casoscovid);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnContagiosActionPerformed

    private void btnAplicadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicadasActionPerformed
        JframeAplicadas menuPrincipal = new JframeAplicadas(this.vacunasAplicadas);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnAplicadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeMedico(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicadas;
    private javax.swing.JButton btnContagios;
    private javax.swing.JButton btnSalario;
    private javax.swing.JButton btnVacunas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
